services:

  ollama:
    image: ollama/ollama:latest
    ports:
     - 11434:11434
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
      - ./start_ollama.sh:/start_ollama.sh
    restart: always
    entrypoint: [ "/usr/bin/bash", "/start_ollama.sh" ]
    networks:
      - web

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080

    environment:
      SEARXNG_URL: http://searxng:8080
      # ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 4
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 12
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
      OLLAMA_BASE_URL: "http://ollama:11434"
      # SEARXNG_QUERY_URL: http://searxng.local/search?q=<query>

    volumes:
      - open-webui:/app/backend/data
    depends_on:
     - searxng
     - ollama
    restart: always
    networks:
      - web

  searxng:
    image: searxng/searxng:latest
    ports:
      - '8080:8080'
    networks:
      - web
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml

    restart: always

volumes:
  ollama: {}
  open-webui: {}
  searxng: {}

networks:
  web:
