services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
      - ./start_ollama.sh:/start_ollama.sh
    restart: always
    entrypoint: [ "/usr/bin/bash", "/start_ollama.sh" ]
    networks:
      - web

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080

    environment:
      SEARXNG_URL: "http://searxng:8080"
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 4
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 12
      OLLAMA_BASE_URL: "http://ollama:11434"

    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: always
    networks:
      - web

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - 9099:9099
    restart: always
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pipelines:/app/pipelines
    depends_on:
      - webui
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: your_database
      DB_USER: your_username
      DB_PASSWORD: your_password

volumes:
  ollama: {}
  open-webui: {}

networks:
  web:
